[[procedure]]
name = "automatic-sync"

[procedure.config]
schedule_format = "Cron"
schedule = "0 * * * * ?"
schedule_enabled = true
schedule_timezone = "Europe/Paris"
schedule_alert = false
failure_alert = true
webhook_enabled = false

[[procedure.config.stage]]
name = "sync le depot"
enabled = true

executions = [
  {
    execution.type = "RunSync",
    execution.params.sync = "proxmox-configuration-sync",
    enabled = true
  }
]

[[stack]]
name = "kanboard"
deploy = true

[stack.config]
server = "Local"
git_provider = "github.com"
git_account = ""
repo = "blavogiez-org/proxmox-configuration"
branch = "main"
clone_path = "/etc/komodo/stacks/kanboard"
run_directory = "/etc/komodo/stacks/kanboard/services/kanboard"
file_paths = ["docker-compose.yml"]
webhook_enabled = false
auto_pull = true

[stack.config.pre_deploy]
command = """
[ -f .env ] || (KANBOARD_DB_PASSWORD="$(openssl rand -hex 32)" && echo "KANBOARD_DB_PASSWORD=$KANBOARD_DB_PASSWORD" > .env)
"""
