[[stack]]
name = "kanboard"
deploy = true

[stack.config]
server = "Local"
git_provider = "github.com"
repo = "jobacogiez-org/proxmox-gitops"
branch = "20-déploiement-komodo-poc"
run_directory = "services/kanboard-poc-komodo"
file_paths = ["docker-compose.yaml"]
