# --- CONFIGURATION GLOBALE ---
domain: "votre-domaine.fr"
timezone: "Europe/Paris"
admin_user: "admin"

# --- INFRASTRUCTURE ---
proxmox:
  endpoint: "https://pve.home.arpa:8006/api2/json"
  node: "homelab"
  storage: "local-lvm"
  ssh_user: "root"
