hostname: ${hostname}
preserve_hostname: false

users:
  - name: admin
    groups: docker
    sudo: ALL=(ALL) NOPASSWD:ALL
    shell: /bin/bash
    ssh_authorized_keys:
      - ${ssh_public_key}

packages:
  - qemu-guest-agent
  - curl

write_files:
  - path: /opt/traefik/docker-compose.yml
    content: |
      services:
        traefik:
          image: traefik:v3.7
          command:
            - "--api.insecure=true"
            - "--providers.docker=true"
            - "--providers.docker.exposedbydefault=false"
            - "--providers.docker.network=proxy"
            - "--entrypoints.web.address=:80"
          ports:
            - "80:80"
            - "8080:8080"
          volumes:
            - /var/run/docker.sock:/var/run/docker.sock:ro
          networks: 
            - proxy
      networks:
        proxy:
          external: true

runcmd:
  - systemctl enable --now qemu-guest-agent
  - curl -fsSL https://get.docker.com | sudo sh
  - docker network create proxy || true
  - cd /opt/traefik
  - docker compose up -d
  - cd /opt/komodo
  - wget https://raw.githubusercontent.com/moghtech/komodo/main/compose/mongo.compose.yaml
  - docker compose -p komodo -f mongo.compose.yaml --env-file compose.env up -d