#cloud-config
# alloy a besoin du hostname pour bien envoyer les logs
hostname: ${hostname}
preserve_hostname: false

users:
  - name: admin
    groups: docker
    sudo: ALL=(ALL) NOPASSWD:ALL
    shell: /bin/bash
    ssh_authorized_keys:
      - ${ssh_public_key}
packages:
  - qemu-guest-agent
  - libicu76
  - git
  - curl 
  - tree
  - pip 
  - pipx 
  - gpg
  - python3
runcmd: 
  - systemctl enable qemu-guest-agent
  - systemctl start qemu-guest-agent
  - curl -fsSl https://get.docker.com | sh
  # generation credentials aleatoires une seule fois (on en aura jamais besoin car c'est interne. c'est juste pour pas hardcoder en clair tout de meme)
  - sudo mkdir -p /opt/terraform-backend
  - POSTGRES_PASSWORD="$(openssl rand -hex 32)" && echo "POSTGRES_PASSWORD=$POSTGRES_PASSWORD" | sudo tee -a /opt/terraform-backend/.env >/dev/null
  - APP_SECRET="$(openssl rand -hex 32)" && echo "APP_SECRET=$APP_SECRET" | sudo tee -a /opt/terraform-backend/.env >/dev/null


