apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
    name: ecodrop-secret
    annotations:
        argocd.argoproj.io/sync-wave: "-1"
spec:
    secretTemplates:
        - name: ecodrop-secret
          stringData:
            POSTGRES_USER: ENC[AES256_GCM,data:RvAEAhopn8dHQPXMwsTwfyVHSw==,iv:9lKI3fQV3yAtz/HyWhFAlacgUpYWaAAtfAOWfEi9BYI=,tag:JZCcaR4gwM4HGwKU6L0d1w==,type:str]
            POSTGRES_PASSWORD: ENC[AES256_GCM,data:9ifbiB8zDkI=,iv:Iaml0Eio07J1b5By8/Dee+wP5CKdNrrFTTqNyEUFa1g=,tag:FrcpPlwaSqO2YW66Y1Jz2A==,type:str]
            POSTGRES_DB: ENC[AES256_GCM,data:02J7tA==,iv:2MKh67z4Fu6JeqSkYShCuY1EDwE6hqXYxxaZ1ldrba4=,tag:efcIEDZVz31YPCyFstNipQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1e3s582qyex8rek06cjqsn8ft2r98anhrn9nc7axd7vyz3zx9tycqurnuce
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBMWElrSGNwYWtKNzViYnlC
            QVFlSG9TVmZnV1RXS3h3aG1Qb2NIUVJYcmdrCjFEaWJjWnVKUTVLdTB2WlpSMmZz
            VmdJMC9FdFVkTUxvNU5Ub0Y3K2NIZkEKLS0tIFo2dFVETklnSEpHN2plVE9TUkhu
            MzRHczB1K3RmMjVWcWRNK1VsMzQ5b2sKkf9WwMQwuCNDO37SnuVYVqkpVBwDhTqs
            gW/ROzhLIGPyJvvHSsjb4dYW7jF5fEeGA4JDMRzNRQsbMG19mTmOKQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-09-05T13:58:30Z"
    mac: ENC[AES256_GCM,data:uXT705Cd88iKbq0978HfJ0Kc1u/tp6ptlcVDRstmU5Kls44FlJw4X+mGtlT7C3KNITiilqzeFdwi/hYTBdyk4Qn3gDfsfMOaDR8gCvj3ai6M5xuSSvDb5SWBhy/rQZiNFyoVdWsnfmB1UUh5kjB59+SRJFKev+EZ4xZ7r8HI5oo=,iv:KM8w92VtO8jIik34QT6IwzbwSE8iahxukH2SWvhuNhI=,tag:hzsNzL08NbJQqf9F7NQQLA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.4
