vault:
    proxmox_api_token: ENC[AES256_GCM,data:ApVlQxYA1dBGKgUqeG2VwpcZ2TtMiZsjRA==,iv:V6p/rXGm/U9BM26QV6XBC0QZ0wcs3+PcuBh8AuB6bnQ=,tag:PK+L6fywfjkIwtG8e0egGg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1e3s582qyex8rek06cjqsn8ft2r98anhrn9nc7axd7vyz3zx9tycqurnuce
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBBSktOdjl3K0ZKc1ExTGl3
            QlhESmFQWk1XUDdpTnJGUmNOMms3cWQ1UXdNCm4zdXRZZGgrR2R3WCtINElvaTV5
            ZUs3bVdOWTVpd0w4SU1EdXlvWXhlVzQKLS0tIDBPZUgyTXhtMnN6TkJsdGJzUEdI
            c05BcE84QjdxVE9PTUdlUnpIbGRHQjQKQN9xk2xoc2PNPGvYRCahTIr1FkMSxG9R
            +guXk3vhaYMKH6iAikGFYbEUebD9yXRIQVdYbfsUePJ5GSCa4exgwQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-09-03T14:25:04Z"
    mac: ENC[AES256_GCM,data:cN/kkUgs+byf7BQZpYr9twUoDVidw9XYGA0Y6VhragYBfVnPuaOfVIhKyeNFqqqBU1/HBgSQz5SSZM8WIiChJR8C8Nr4GLtDkHjLUKy62VPK08u6U5CgGUj95LrrMb3/ru4fPlQ0yFGQuDAN+NW8Xh/9pK8YtNOBMfkOpqEDMGs=,iv:GVjqI651Xmj47/ULAANKr+t5vE0XkHlSlVtr9LUEqDw=,tag:e0uI5xmAJ2xsX8yk/Nktow==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.9.4
