# a mettre sur l'hote proxmox (et de là, rien à faire d'autre)
volumes:
  etc_wireguard:

services:
  wg-easy:
    image: ghcr.io/wg-easy/wg-easy:15.3.0
    container_name: wg-easy
    network_mode: host
    environment:
      - WG_HOST=192.168.1.100
      - PORT=51821
      - WG_PORT=51820
      - WG_DEFAULT_DNS=1.1.1.1
      - WG_ALLOWED_IPS=10.8.0.0/24, 192.168.10.0/24, 172.16.10.0/24
      - UI_TRAFFIC_STATS=true
    volumes:
      - etc_wireguard:/etc/wireguard
      - /lib/modules:/lib/modules:ro
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    devices:
      - /dev/net/tun:/dev/net/tun