- hosts: coredns
  become: true
  vars_files:
    - ../../settings.yml
  vars:
    coredns_remote_dir: "/opt/coredns"
    coredns_local_dir: "{{ playbook_dir }}/../../services/coredns"

  tasks:
    - name: S'assurer que les répertoires existent
      ansible.builtin.file:
        path: "{{ item }}"
        state: directory
        mode: '0755'
      loop:
        - "{{ coredns_remote_dir }}"
        - "{{ coredns_remote_dir }}/config"

    - name: Copier le compose
      ansible.builtin.copy:
        src: "{{ coredns_local_dir }}/{{ item }}"
        dest: "{{ coredns_remote_dir }}/{{ item }}"
        mode: '0644'
      loop:
        - docker-compose.yml
      register: docker_files

    - name: Générer le fichier Corefile
      ansible.builtin.template:
        src: "{{ coredns_local_dir }}/config/Corefile.j2"
        dest: "{{ coredns_remote_dir }}/config/Corefile"
        mode: '0644'
      register: corefile

    - name: Vérifier si le conteneur Coredns est en cours d'exécution
      ansible.builtin.command: docker ps --filter "name=coredns" --filter "status=running" -q
      register: coredns_running
      changed_when: false

    - name: Reconstruire et redémarrer Coredns si ca a changé
      community.docker.docker_compose_v2:
        project_src: "{{ coredns_remote_dir }}"
        build: always
        state: present
      when: docker_files.changed or corefile.changed or coredns_running.stdout == ""

    - name: Redémarrer Coredns si le Corefile a changé
      community.docker.docker_compose_v2:
        project_src: "{{ coredns_remote_dir }}"
        state: restarted
      when:
        - corefile.changed
        - coredns_running.stdout != ""
