# but de ce playbook : déployer n'importe quel compose tel que décrit dans la structure services
# trame : on copie les fichiers dans /opt/{service}, on template les fichiers, et selon si ça a changé ou non on redémarre la stack
- hosts: "{{ host }}"
  become: true
  vars_files:
    - ../../settings.yml
  vars:
    # target_service attendu en argument
    target_remote_dir: "/opt"
    target_local_dir: "{{ playbook_dir }}/../../services/{{ target_service }}"

  tasks:
    # il faut la library python 'hvac' sur la machine qui lance le playbook (pas la machine cible) apt install python3-hvac
    - name: vérifier si la machine qui lance a la library python 'hvac' ; c'est requis pour acceder au vault dans le playbook
      ansible.builtin.apt:
        name: python3-hvac
        state: present
        update_cache: true
      delegate_to: localhost
      become: true # donc lancer ansible avec l'option -K (ca va demander le mot de passe d'élévation)
      run_once: true
    
    # actuellement on a du https interne car on a pas encore fait les certificats publics pour le réseau privé, d'où le validate_certs
    - name: charger les secrets openbao relatifs au service (et uniquement ceux-là)
      ansible.builtin.set_fact:
        vault: >-
          {{
            {
              target_service: lookup(
                'community.hashi_vault.vault_kv2_get',
                target_service,
                engine_mount_point='secret',
                url='https://192.168.10.15',
                validate_certs=false,
                token_path=lookup('env', 'HOME'),
                token_file='.vault-token'
              ).secret
            }
          }}
      # pour debug on peut enlever no log
      no_log: true
      ignore_errors: true
      # si il y a un probleme de token, tenter .bao-token plutot que .vault-token
    # cette tache évite la redondance pour la configuration des sites regardés en générant la configuration à partir des sites de Caddy
    # j'ai essayé avec des spotters de certs (= surveiller les sous domaines d'un domaine) mais c'est en retard sur la réalité
    - name: exclusif au service monitoring ; on charge les sites en variable pour générer le template des sites à surveiller le statut (voir monitoring/gatus/config/sites.yaml.j2)
      ansible.builtin.shell:
        # on recolte les domaines définis dans les labels Traefik d'un conteneur, et on ajoute https au début post extraction, car Traefik veut un hote pur et pas https avant
        # services/dummy-service/docker-compose.yml:      - "traefik.http.routers.kanboard.rule=Host(`apercu-site.blavogiez.fr`)"
        cmd: !unsafe | 
          find . -name 'docker*compose*.y*ml*' -exec grep "Host(" {} \; | cut -d '`' -f2 | sed 's|^|https://|g'
          find services/caddy/sites -name '*.conf.j*' -exec grep '{{ domain }}' {} \; | grep -v '[#*]' | sed 's/ {$//g'
        # unsafe sert à ne pas interpreter les expressions jinja récoltées. Elles doivent etre interprétées plus tard, au moment du déploiement uniforme
        # et on affiche tous les sites décrits dans Caddy, en excluant ceux commentés et les wildcards. Le dernier sed enleve le début d'accolade qui termine la ligne
        chdir: "{{ playbook_dir }}/../.."
      when: target_service == 'monitoring'
      delegate_to: localhost
      register: retrieved_websites
    
    - name: afficher les sites trouvés à monitorer par gatus
      ansible.builtin.debug:
        var: retrieved_websites.stdout_lines
      when: target_service == 'monitoring'

    - name: S'assurer que le répertoire existe
      ansible.builtin.file:
        path: "{{ target_remote_dir }}"
        state: directory
        mode: '0755'

    - name: Copier l'ensemble du service vers le remote
      ansible.builtin.copy:
        src: "{{ target_local_dir }}"
        dest: "{{ target_remote_dir }}"
        mode: '0644'
      register: target_remote_stack

    # pour lse secrets, le Jinja2 attend typiquement vault.{{ service }}.{{ nom clé }}
    - name: générer les éventuels templates (*.j2)
      ansible.builtin.template:
        src: "{{ item.src }}"
        dest: "{{ target_remote_dir }}/{{ target_service }}/{{ item.path | regex_replace('\\.j2$', '') }}"
        mode: '0644'
      loop: "{{ query('community.general.filetree', target_local_dir) }}"
      when: item.state == 'file' and item.path.endswith('.j2')
      register: target_templates

    - name: S'assurer que la stack est présente et démarrée
      community.docker.docker_compose_v2:
        project_src: "{{ target_remote_dir }}/{{ target_service }}"
        state: present
      register: target_compose

    - name: Redémarrer la stack si un fichier monté a changé
      community.docker.docker_compose_v2:
        project_src: "{{ target_remote_dir }}/{{ target_service }}"
        state: restarted
      when:
        - target_remote_stack.changed or target_templates.changed
