- hosts: monitoring
  become: true
  vars:
    monitoring_remote_dir: "/opt/monitoring"
    monitoring_local_dir: "{{ playbook_dir }}/../../monitoring"

  tasks:
    - name: Copier le dossier monitoring
      ansible.builtin.copy:
        src: "{{ monitoring_local_dir }}/"
        dest: "{{ monitoring_remote_dir }}"
        mode: preserve

    - name: Démarrer monitoring
      community.docker.docker_compose_v2:
        project_src: "{{ monitoring_remote_dir }}"
        state: present
