---
- hosts: caddy
  become: true
  vars:
    websites_remote_dir: "/var/www/{{ caller_repository }}"
    sites_remote_dir: "/opt/caddy/sites/{{ caller_repository }}"
    html_websites: "{{ websites | selectattr('type', 'equalto', 'html') | list }}"

  tasks:
    - name: Copier les websites HTML
      ansible.builtin.copy:
        src: "{{ caller_dir }}/{{ item.path }}/"
        dest: "{{ websites_remote_dir }}/{{ item.domains[0] }}/"
        mode: '0644'
        directory_mode: '0755'
      loop: "{{ html_websites }}"

    - name: Créer les fichiers Caddy des websites HTML
      ansible.builtin.template:
        src: "{{ playbook_dir }}/../../caddy/website.conf.j2"
        dest: "{{ sites_remote_dir }}/{{ item.1 }}.conf"
        mode: '0644'
      loop: "{{ html_websites | subelements('domains') }}"
      vars:
        website: "{{ item.0 }}"
        domain: "{{ item.1 }}"
