- hosts: caddy
  become: true
  vars_files:
    - ../../settings.yml
  vars:
    caddy_remote_dir: "/opt/caddy"
    caddy_local_dir: "{{ playbook_dir }}/../../services/caddy"

  tasks:
    - name: S'assurer que les répertoires existent
      ansible.builtin.file:
        path: "{{ item }}"
        state: directory
        mode: '0755'
      loop:
        - "{{ caddy_remote_dir }}"
        - "{{ caddy_remote_dir }}/sites"

    - name: Copier les fichiers Docker (Dockerfile, compose)
      ansible.builtin.copy:
        src: "{{ caddy_local_dir }}/{{ item }}"
        dest: "{{ caddy_remote_dir }}/{{ item }}"
        mode: '0644'
      loop:
        - Dockerfile
        - docker-compose.yml
      register: docker_files

    - name: Copier la configuration Caddy
      ansible.builtin.copy:
        src: "{{ caddy_local_dir }}/{{ item }}"
        dest: "{{ caddy_remote_dir }}/{{ item }}"
        mode: '0644'
      loop:
        - Caddyfile
      register: main_config

    - name: supprimer le contenu des sites pour que le git soit vraiment la source de vérité (= pas de site supplémentaire en remote autorisé)
      ansible.builtin.shell:
        cmd: rm -rf {{ caddy_remote_dir }}/sites/*

    # https://docs.ansible.com/projects/ansible/latest/collections/ansible/builtin/fileglob_lookup.html 
    # ressource utile pour bien itérer dessus
    - name: Générer les sites de template
      ansible.builtin.template:
        src: "{{ caddy_local_dir }}/sites/{{ item | basename }}"
        dest: "{{ caddy_remote_dir }}/sites/{{ item | basename | regex_replace('\\.j2$', '') }}"
        mode: '0644'
      with_fileglob: 
        - "{{ caddy_local_dir }}/sites/*.conf.j2"
      register: sites_config

    - name: Vérifier si le conteneur Caddy est en cours d'exécution
      ansible.builtin.command: docker ps --filter "name=caddy" --filter "status=running" -q
      register: caddy_running
      changed_when: false

    - name: Reconstruire et redémarrer Caddy (si Dockerfile a changé ou si éteint)
      community.docker.docker_compose_v2:
        project_src: "{{ caddy_remote_dir }}"
        build: always
        state: present
      when: docker_files.changed or caddy_running.stdout == ""

    - name: Recharger la configuration Caddy à chaud (si config a changé et Dockerfile inchangé)
      ansible.builtin.command:
        cmd: docker exec caddy caddy reload --config /etc/caddy/Caddyfile
      when: 
        - (main_config.changed or sites_config.changed)
        - not docker_files.changed
        - caddy_running.stdout != ""
