---
- hosts: caddy
  become: true
  vars:
    websites_remote_dir: "/var/www/{{ caller_repository }}"
    build_remote_dir: "/var/www/build/{{ caller_repository }}"
    sites_remote_dir: "/opt/caddy/sites/{{ caller_repository }}"
    vite_websites: "{{ websites | selectattr('type', 'equalto', 'vite') | list }}"

  tasks:
    - name: Installer nodejs et npm
      ansible.builtin.apt:
        name:
          - nodejs
          - npm
        state: present
        update_cache: true
      when: vite_websites | length > 0

    - name: Copier les sources Vite
      ansible.builtin.copy:
        src: "{{ caller_dir }}/{{ item.path }}/"
        dest: "{{ build_remote_dir }}/{{ item.domains[0] }}/"
        mode: '0644'
        directory_mode: '0755'
      loop: "{{ vite_websites }}"

    - name: Installer les dépendances Vite
      ansible.builtin.command:
        cmd: npm ci
        chdir: "{{ build_remote_dir }}/{{ item.domains[0] }}"
      loop: "{{ vite_websites }}"

    - name: Build les websites Vite
      ansible.builtin.command:
        cmd: npm run build
        chdir: "{{ build_remote_dir }}/{{ item.domains[0] }}"
      loop: "{{ vite_websites }}"

    - name: Copier les builds Vite
      ansible.builtin.copy:
        src: "{{ build_remote_dir }}/{{ item.domains[0] }}/dist/"
        dest: "{{ websites_remote_dir }}/{{ item.domains[0] }}/"
        remote_src: true
        mode: '0644'
        directory_mode: '0755'
      loop: "{{ vite_websites }}"

    - name: Créer les fichiers Caddy des websites Vite
      ansible.builtin.template:
        src: "{{ playbook_dir }}/../../services/caddy/website.conf.j2"
        dest: "{{ sites_remote_dir }}/{{ item.1 }}.conf"
        mode: '0644'
      loop: "{{ vite_websites | subelements('domains') }}"
      vars:
        website: "{{ item.0 }}"
        domain: "{{ item.1 }}"
