# Repris de https://grafana.com/docs/alloy/latest/set-up/install/ansible/

- name: Install Alloy
  hosts: all
  become: true

  handlers:
    - name: Restart containerd
      ansible.builtin.systemd_service: { name: containerd, state: restarted }
  tasks:
    - name: Install Alloy
      ansible.builtin.include_role:
        name: grafana.grafana.alloy
      vars:
        alloy_config: "{{ lookup('ansible.builtin.file', playbook_dir ~ '/../../services/monitoring/alloy/config.alloy') }}"
        alloy_env_file_vars:
          CUSTOM_ARGS: "--server.http.listen-addr=127.0.0.1:12345"
        alloy_user_groups:
          - systemd-journal
          - adm
          - docker
    # acces aux logs docker
    - name: Read Docker group
      ansible.builtin.getent: { database: group, key: docker }
    - name: Give Docker group access to containerd
      community.general.ini_file: { path: /etc/containerd/config.toml, section: grpc, option: gid, value: "{{ getent_group.docker[1] }}" }
      notify: Restart containerd
