---
- hosts: caddy
  become: true
  vars:
    caddy_remote_dir: "/opt/caddy"
    websites_remote_dir: "/var/www/{{ caller_repository }}"
    build_remote_dir: "/var/www/build/{{ caller_repository }}"
    sites_remote_dir: "{{ caddy_remote_dir }}/sites/{{ caller_repository }}"
    sites_remote_file: "{{ caddy_remote_dir }}/sites/{{ caller_repository }}.conf"

  tasks:
    - name: Supprimer l'ancien déploiement du dépôt
      ansible.builtin.file:
        path: "{{ item }}"
        state: absent
      loop:
        - "{{ websites_remote_dir }}"
        - "{{ build_remote_dir }}"
        - "{{ sites_remote_dir }}"
        - "{{ sites_remote_file }}"

    - name: S'assurer que les répertoires existent
      ansible.builtin.file:
        path: "{{ item }}"
        state: directory
        mode: '0755'
      loop:
        - "{{ websites_remote_dir }}"
        - "{{ build_remote_dir }}"
        - "{{ sites_remote_dir }}"

    - name: Créer l'import Caddy du dépôt
      ansible.builtin.copy:
        content: "import /etc/caddy/sites/{{ caller_repository }}/*.conf\n"
        dest: "{{ sites_remote_file }}"
        mode: '0644'
