---
- name: récuper le certificat interne du Caddy de Vault (C est que un certificat public)
  hosts: vault
  become: true
  tasks:
    - name: on recupere depuis le conteneur
      ansible.builtin.shell:
        cmd: |
          docker cp caddy:/data/caddy/pki/authorities/local/root.crt /tmp/vault-caddy-root.crt
      changed_when: false

    - name: on le stock sur le controleur en attendant de le passer à caddy
      ansible.builtin.fetch:
        src: /tmp/vault-caddy-root.crt
        dest: /tmp/vault-caddy-root.crt
        flat: true

- name: Installer la CA interne qu on vient de recuperer sur le Caddy central
  hosts: caddy
  become: true
  tasks:
    - name: Créer le répertoire des ca internes
      ansible.builtin.file:
        path: /opt/caddy/certs
        state: directory
        owner: "{{ ansible_user }}"
        group: "{{ ansible_user }}"
        mode: '0755'

    - name: Copier le certificat racine du Caddy Vault
      ansible.builtin.copy:
        src: /tmp/vault-caddy-root.crt
        dest: /opt/caddy/certs/vault-caddy-root.crt
        owner: "{{ ansible_user }}"
        group: "{{ ansible_user }}"
        mode: '0644'
      register: cert_on_caddy

    - name: Redémarrer le Caddy central
      community.docker.docker_compose_v2:
        project_src: /opt/caddy
        state: restarted
      when:
        - cert_on_caddy.changed
