# approche bourrin avec 3 conteneurs en attendant de déployer le helm clean
services:
  containerized-runner-1:
    image: local/github-runner:ubuntu-noble-ansible
    build:
      context: .
      dockerfile: Dockerfile
    container_name: containerized-runner-1
    restart: unless-stopped
    privileged: true
    environment:
      REPO_URL: "https://github.com/blavogiez-org/proxmox-configuration"
      RUNNER_SCOPE: "repo"
      RUNNER_NAME: "containerized-runner-1"
      RUNNER_WORKDIR: "/tmp/runner/work"
      LABELS: "self-hosted,komodo"
      RUNNER_TOKEN: "${GITHUB_RUNNER_TOKEN:?GITHUB_RUNNER_TOKEN is required}"
      CONFIGURED_ACTIONS_RUNNER_FILES_DIR: "/runner/data"
      DISABLE_AUTOMATIC_DEREGISTRATION: "true"
      START_DOCKER_SERVICE: "true"
      UNSET_CONFIG_VARS: "true"
    tmpfs:
      - /tmp
    volumes:
      - runner-tmp:/tmp/runner
      - runner-data:/runner/data
      - runner-docker:/var/lib/docker
    networks:
      - runner_net

  containerized-runner-2:
    image: local/github-runner:ubuntu-noble-ansible
    build:
      context: .
      dockerfile: Dockerfile
    container_name: containerized-runner-2
    restart: unless-stopped
    privileged: true
    environment:
      REPO_URL: "https://github.com/blavogiez-org/proxmox-configuration"
      RUNNER_SCOPE: "repo"
      RUNNER_NAME: "containerized-runner-2"
      RUNNER_WORKDIR: "/tmp/runner/work"
      LABELS: "self-hosted,komodo"
      RUNNER_TOKEN: "${GITHUB_RUNNER_TOKEN:?GITHUB_RUNNER_TOKEN is required}"
      CONFIGURED_ACTIONS_RUNNER_FILES_DIR: "/runner/data"
      DISABLE_AUTOMATIC_DEREGISTRATION: "true"
      START_DOCKER_SERVICE: "true"
      UNSET_CONFIG_VARS: "true"
    tmpfs:
      - /tmp
    volumes:
      - runner-tmp-2:/tmp/runner
      - runner-data-2:/runner/data
      - runner-docker-2:/var/lib/docker
    networks:
      - runner_net

  containerized-runner-3:
    image: local/github-runner:ubuntu-noble-ansible
    build:
      context: .
      dockerfile: Dockerfile
    container_name: containerized-runner-3
    restart: unless-stopped
    privileged: true
    environment:
      REPO_URL: "https://github.com/blavogiez-org/proxmox-configuration"
      RUNNER_SCOPE: "repo"
      RUNNER_NAME: "containerized-runner-3"
      RUNNER_WORKDIR: "/tmp/runner/work"
      LABELS: "self-hosted,komodo"
      RUNNER_TOKEN: "${GITHUB_RUNNER_TOKEN:?GITHUB_RUNNER_TOKEN is required}"
      CONFIGURED_ACTIONS_RUNNER_FILES_DIR: "/runner/data"
      DISABLE_AUTOMATIC_DEREGISTRATION: "true"
      START_DOCKER_SERVICE: "true"
      UNSET_CONFIG_VARS: "true"
    tmpfs:
      - /tmp
    volumes:
      - runner-tmp-3:/tmp/runner
      - runner-data-3:/runner/data
      - runner-docker-3:/var/lib/docker
    networks:
      - runner_net

volumes:
  runner-tmp:
  runner-data:
  runner-docker:
  runner-tmp-2:
  runner-data-2:
  runner-docker-2:
  runner-tmp-3:
  runner-data-3:
  runner-docker-3:

networks:
  runner_net:
    driver: bridge
