services:
  openbao:
    image: openbao/openbao:latest
    container_name: openbao
    cap_add:
      - IPC_LOCK
    expose:
      - "8200"
    # il faut éviter de faire ça car ca ouvrirait le port 8200 sur la machine
    # ports:
    #   - "8200:8200" # l'ui web, on peut pointer dessus
    volumes:
      - ./openbao/config:/etc/openbao
      - ./openbao/file:/openbao/file
    command: server -config=/etc/openbao/openbao.hcl
  caddy:
    image: caddy:2
    container_name: caddy
    volumes:
      - ./caddy:/etc/caddy
      - caddy_data:/data
      - caddy_config:/config
    ports:
      - "80:80"
      - "443:443"

volumes:
  caddy_data:
  caddy_config: