# utilisation de https://bjw-s-labs.github.io/helm-charts 
# c'est un template de helm chart fait pour décrire n'importe quelle application.
defaultPodOptions:
  securityContext:
    runAsUser: 10000
    runAsGroup: 10000
    runAsNonRoot: true
    fsGroup: 10000
    fsGroupChangePolicy: OnRootMismatch

controllers:
  vaultwarden:
    strategy: Recreate
    containers:
      main:
        image:
          repository: vaultwarden/server
          tag: latest
        env:
          DATA_FOLDER: "/config"
service:
  vaultwarden:
    controller: vaultwarden
    ports:
      http:
        port: 80

persistence:
  config:
    type: persistentVolumeClaim
    accessMode: ReadWriteOnce
    size: 2Gi
    advancedMounts:
      vaultwarden:
        main:
          - path: /config

route:
  vaultwarden:
    enabled: true
    kind: HTTPRoute
    parentRefs:
      - name: traefik-gateway
        namespace: traefik
    hostnames: 
      - vaultwarden-vide-poc.priv.blavogiez.fr 
    rules: 
      - matches:
          - path: 
              type: PathPrefix
              value: /
        backendRefs:
          - name: vaultwarden 
            port: 80

