#cloud-config
hostname: ${hostname}
preserve_hostname: false


users:
  - name: admin
    groups: docker
    sudo: ALL=(ALL) NOPASSWD:ALL
    shell: /bin/bash
    ssh_authorized_keys:
      - ${ssh_public_key}

packages:
  - qemu-guest-agent
  - curl
  - openssl

# on suit strictement https://docs.goauthentik.io/install-config/install/docker-compose/
runcmd:
  - systemctl enable --now qemu-guest-agent
  - curl -fsSL https://get.docker.com | sudo sh