# cf config.alloy dans dossier monitoring
# cf https://grafana.com/docs/alloy/latest/set-up/install/kubernetes/
# cf https://grafana.com/docs/alloy/latest/configure/kubernetes/
alloy:
  enableReporting: false
  configMap:
    content: |
      loki.write "monitoring" {
        endpoint {
          url = "http://192.168.10.14:3100/loki/api/v1/push"
        }
      }

      discovery.kubernetes "pods" {
        role = "pod"
      }

      discovery.relabel "pod_logs" {
        targets = discovery.kubernetes.pods.targets

        rule {
          source_labels = ["__meta_kubernetes_namespace"]
          target_label  = "namespace"
        }
        rule {
          source_labels = ["__meta_kubernetes_pod_name"]
          target_label  = "pod"
        }
        rule {
          source_labels = ["__meta_kubernetes_pod_container_name"]
          target_label  = "container"
        }
        rule {
          source_labels = ["__meta_kubernetes_pod_label_app_kubernetes_io_name"]
          target_label  = "app"
        }
      }

      loki.source.kubernetes "pods" {
        targets    = discovery.relabel.pod_logs.output
        forward_to = [loki.write.monitoring.receiver]
      }

      prometheus.remote_write "monitoring" {
        endpoint {
          url = "http://192.168.10.14:9090/api/v1/write"
        }
      }

      prometheus.exporter.unix "node" {}

      prometheus.scrape "node" {
        targets    = prometheus.exporter.unix.node.targets
        forward_to = [prometheus.remote_write.monitoring.receiver]
      }
