#cloud-config
hostname: ${hostname}
preserve_hostname: false

users:
  - name: admin
    groups: docker
    sudo: ALL=(ALL) NOPASSWD:ALL
    shell: /bin/bash
    ssh_authorized_keys:
      - ${ssh_public_key}


# vu que c'est vault, idéalement limiter au maximum les paquets installés pour limiter les vulnérabilités
packages:
  - qemu-guest-agent
  - curl
  - git

runcmd:
  - systemctl enable --now qemu-guest-agent
  - curl -fsSL https://get.docker.com | sh
  - mkdir -p /opt/vault/openbao/file
  - chown -R 100:1000 /opt/vault/openbao/file
