name: Construire + pousser une image sur cr.priv.blavogiez.fr



on:
  push:
#    branches: main
  workflow_dispatch:

permissions:
  contents: read

jobs:
  login-build-push:
    runs-on: self-hosted
    steps: 
    # CF https://github.com/hashicorp/vault-action
    -   name: Import Secrets
        id: import-secrets
        uses: hashicorp/vault-action@v4
        with:
            url: https://vault.priv.blavogiez.fr
            token: ${{ secrets.BAO_CR_TOKEN }}
            secrets: |
                secret/data/zot publisher_password | CR_PUBLISHER_PASSWORD ;
      
    # CF https://github.com/docker/login-action
    -   name: login sur cr.priv.blavogiez.fr avec publisher, user limité 
        uses: docker/login-action@v4
        with:
          registry: cr.priv.blavogiez.fr
          username: publisher
          password: ${{ env.CR_PUBLISHER_PASSWORD }}

    # CF https://github.com/docker/build-push-action
    -  
        uses: actions/checkout@v4
    -
        name: Build and push
        uses: docker/build-push-action@v7
        with:
          context: services/caddy
          push: true
          tags: cr.priv.blavogiez.fr/apps/caddy-acme-ratelimit:latest
