# sample d'appel de construction d'image sur le Container registry hébergé sur une LXC sur proxmox
name: build + push sur cr.priv.blavogiez.fr avec vault loading (Test pour un exemple qui reste)

on:
  push:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build-push-image:
    uses: blavogiez-org/proxmox-configuration/.github/workflows/callable-build-push-image.yml@6-container-registry-harbor
    with:
      context: services/caddy
      tag: cr.priv.blavogiez.fr/apps/caddy-acme-ratelimit:latest
    secrets:
      BAO_CR_TOKEN: ${{ secrets.BAO_CR_TOKEN }}
