name: Appel d'un déploiement front (pour exemple)

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  deploy:
    uses: blavogiez-org/proxmox-configuration/.github/workflows/frontend-deploy-website.yml@main
    secrets: inherit
