# https://hub.docker.com/r/bridgecrew/checkov/tags
# https://github.com/terraform-linters/tflint/pkgs/container/tflint

# on fait en docker car les runners self hosted peuvent différer de packages
---
name: Analyse statique du dépôt (linters Checkov / TFLint)
on:
  push:
    branches: [main]
  workflow_dispatch:
jobs:
  static-analysis:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4

      # on monte simplement le dépôt en bind mount
      - name: Analyse checkov
        run: |
          docker run --rm -v "$PWD:/repo" bridgecrew/checkov:2 -d /repo

      - name: Analyse TFLint
        run: |
          docker run --rm -v "$PWD:/repo" -w /repo ghcr.io/terraform-linters/tflint:latest