# https://hub.docker.com/r/bridgecrew/checkov/tags
---
name: Analyse statique Checkov
on:
  push:
    branches: [main]
  workflow_dispatch:
jobs:
  build:

    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4

      - name: Executer Checkov
        run: |
          docker run --rm -v "$PWD:/repo" bridgecrew/checkov:2 -d /repo