name: "Linters (ce dépôt commun ne déploie rien + runners publics)"

on:
  push:
  pull_request:
  workflow_dispatch:


permissions:
  contents: read
  
jobs:
  static-analysis-checkov:
    runs-on: ubuntu-latest 
    steps:
      - uses: actions/checkout@v4
      - name: Analyse checkov
        run: docker run --rm -v "$PWD:/repo" bridgecrew/checkov:2 -d /repo --quiet

  static-analysis-tflint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Analyse TFLint
        run: docker run --rm -v "$PWD:/repo" -w /repo ghcr.io/terraform-linters/tflint:latest --recursive

  static-analysis-hadolint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Analyse Hadolint
        # Suppression de continue-on-error et no-fail pour rendre le job bloquant
        uses: hadolint/hadolint-action@v3.3.0
        with:
          dockerfile: Dockerfile
          recursive: true
