deployment:
  kind: DaemonSet

providers:
  kubernetesGateway:
    enabled: true

gateway:
  enabled: true
  name: traefik-gateway
  listeners:
    web:
      port: 8000
      protocol: HTTP
      namespacePolicy: All

ports:
  web:
    port: 8000
    hostPort: 80
    exposedPort: 80
