services:
  grafana:
    image: grafana/grafana:13.0.1
    restart: unless-stopped
    ports:
      - "3000:3000"
    volumes:
      - grafana_data:/var/lib/grafana
      - ./grafana/provisioning:/etc/grafana/provisioning:ro
      - ./grafana/dashboards:/var/lib/grafana/dashboards:ro
    environment:
      GF_SECURITY_ADMIN_USER: admin
      GF_SECURITY_ADMIN_PASSWORD: ${GRAFANA_ADMIN_PASSWORD}

  loki:
    image: grafana/loki:3.7.0
    restart: unless-stopped
    ports:
      - "3100:3100"
    command: -config.file=/etc/loki/loki.yml
    volumes:
      - ./loki/loki.yml:/etc/loki/loki.yml:ro
      - loki_data:/loki

  prometheus:
    image: prom/prometheus:v3.11.3-distroless
    restart: unless-stopped
    ports:
      - "9090:9090"
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
      - "--storage.tsdb.retention.time=30d"
      - "--web.enable-remote-write-receiver"
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - prometheus_data:/prometheus

  # exterieur au pve pour pas etre trop privilegie
  pve-exporter:
    image: prompve/prometheus-pve-exporter:3.9.0
    restart: unless-stopped
    ports:
      - "9221:9221"
    environment:
      PVE_USER: ${PVE_USER:?PVE_USER must be set}
      PVE_TOKEN_NAME: ${PVE_TOKEN_NAME:?PVE_TOKEN_NAME must be set}
      PVE_TOKEN_VALUE: ${PVE_TOKEN_VALUE:?PVE_TOKEN_VALUE must be set}
      PVE_VERIFY_SSL: "false"

  gatus:
    image: ghcr.io/twin/gatus:stable
    container_name: gatus
    restart: unless-stopped
    ports:
      - "8080:8080"
    environment:
      GATUS_CONFIG_PATH: /config
      GATUS_LOG_LEVEL: INFO
    volumes:
      - ./gatus/config:/config:ro
      - ./gatus/data:/data


volumes:
  grafana_data:
  loki_data:
  prometheus_data:
